import type { CollectionConfig } from 'payload/types';

import { TelephoneField } from '@nouance/payload-better-fields-plugin';
import { tenantAdmins } from './access/tenantAdmins';
import configureStripeOnCustomDomainCreation from './hooks/configureStripeOnCustomDomainCreation';
import generateTenantSubdomains from './hooks/generateSubdomains';

export const Tenants: CollectionConfig = {
  slug: 'tenants',
  access: {
    create: tenantAdmins,
    read: tenantAdmins,
    update: tenantAdmins,
    delete: tenantAdmins,
  },
  hooks: {
    beforeChange: [generateTenantSubdomains, configureStripeOnCustomDomainCreation],
  },
  admin: {
    useAsTitle: 'siteName',
  },
  labels: {
    singular: 'Site',
    plural: 'Sites',
  },
  fields: [
    {
      name: 'siteName',
      label: 'Site Name',
      type: 'text',
      required: true,
    },
    // Customer Relationship Field
    {
      name: 'customer',
      label: 'Customer',
      type: 'relationship',
      relationTo: 'customers',
      hasMany: false,
      admin: {
        position: 'sidebar',
        description: 'The Stripe customer associated with this tenant.',
      },
    },
    // Domains Array Field
    {
      name: "domains",
      label: "Domains",
      type: "array",
      index: true,
      fields: [
        {
          name: "domain",
          type: "text",
          required: true,
          admin: {
            placeholder: "example.com",
            description: "Enter your custom domain (e.g., yourdomain.com) and configure it by adding a CNAME record pointing to your Bloom subdomain.",
          },
        },
        {
          name: "autoGenerated",
          type: "checkbox",
          required: true,
          defaultValue: false,
          admin: {
            description: "This domain was automatically generated for your site by Bloom. All free domains come with free SSL Certificates.",
            readOnly: true,
          },
        },
      ],
    },
    // Email Configuration Relationship Field
    {
      name: 'emailConfig',
      label: 'Email',
      type: 'relationship',
      relationTo: 'email-configs',
      hasMany: false,
      admin: {
        description: 'The email configuration associated with this tenant.',
      },
    },
    // Logo Upload Field
    {
      name: 'logo',
      label: 'Logo',
      type: 'upload',
      relationTo: 'media',
      admin: {
        description: 'Upload your company logo.',
      },
    },
    // Icon Upload Field
    {
      name: 'icon',
      label: 'Icon',
      type: 'upload',
      relationTo: 'media',
      admin: {
        description: 'Upload your company icon. This will be used for the Site Favicon.',
      },
    },
    // Address Details Fields
    {
      name: 'streetAddress',
      label: 'Street Address',
      type: 'text',
      admin: {
        placeholder: '123 Main St.',
        position: 'sidebar',
      },
    },
    {
      name: 'city',
      label: 'City',
      type: 'text',
      admin: {
        placeholder: 'Naples',
        position: 'sidebar',
      },
    },
    // State/Province, Postal Code, and Country Fields
    {
      name: 'state',
      label: 'State/Province',
      type: 'text',
      admin: {
        placeholder: 'Campania',
        position: 'sidebar',
      },
    },
    {
      name: 'postalCode',
      label: 'Postal Code',
      type: 'text',
      admin: {
        placeholder: '80100',
        position: 'sidebar',
      },
    },
    {
      name: 'country',
      label: 'Country',
      type: 'text',
      admin: {
        placeholder: 'Italy',
        position: 'sidebar',
      },
    },
    // Telephone and Business Hours Fields from TelephoneField Plugin
    ...TelephoneField({
      name: 'telephone',
      admin: {
        placeholder: '+1 2133 734 253',
        description: "Add your phone number here.",
        position: 'sidebar',
      },
    }),
    {
      name: 'businessHours',
      label: 'Business Hours',
      type: 'textarea',
      admin: {
        position: 'sidebar',
        description: 'Add your business hours here.',
      },
    },
  ],
};
