export const tenants = [
    {
        company: { name: 'Bloom' },
        domains: [{ domain: 'bloom.localhost.com', autoGenerated: false }],
    },
    {
        company: { name: 'ICA' },
        domains: [{ domain: 'client.localhost.com', autoGenerated: false }],
    },
];
