version: '3'

services:
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  # Uncomment and adjust the service definition below if you need to run an application alongside PostgreSQL.
  # Make sure to replace placeholders with your actual configurations.
  # payload:
  #   image: node:18-alpine
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/home/node/app
  #     - node_modules:/home/node/app/node_modules
  #   working_dir: /home/node/app/
  #   command: sh -c "yarn install && yarn dev"
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env

volumes:
  data:
  node_modules:
